# https://travis-ci.org/#!/phlax/debian-criu

install:
  - make docker

script:
  - ls build | grep criu | grep deb
  - docker images | grep criu-backport
  - >
    docker run --privileged -it
    -v `pwd`/testproc.sh:/tmp/testproc.sh
    -v `pwd`/runtest.sh:/tmp/runtest.sh
    phlax/criu-backport
    /tmp/runtest.sh

before_deploy:
  - echo $DOCKER_API_TOKEN | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make hub-image
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
